const GET_POKEMONS = "GET_POKEMONS";
const GET_POKEMON_ID = "GET_POKEMON_ID";
const CLEAR_ALL = "CLEAR_ALL";
const ORDER_POKEMONS = "ORDER_POKEMONS";
const GET_ORIGIN = "GET_ORIGIN";
const CREATE_POKEMON = "CREATE_POKEMON";
const GET_POKEMONS_TYPE = "GET_POKEMONS_TYPE";
const SEARCH_POKEMON_BY_NAME = "SEARCH_POKEMON_BY_NAME";
const GET_POKEMONS_TYPES_QUANTITY = "GET_POKEMONS_TYPES_QUANTITY";
const ORDER_POKEMONS_ATTACK = "ORDER_POKEMONS_ATTACK";

export {
  GET_POKEMONS,
  GET_POKEMON_ID,
  CLEAR_ALL,
  ORDER_POKEMONS,
  GET_ORIGIN,
  CREATE_POKEMON,
  GET_POKEMONS_TYPE,
  SEARCH_POKEMON_BY_NAME,
  GET_POKEMONS_TYPES_QUANTITY,
  ORDER_POKEMONS_ATTACK,
};